# Generated by Django 4.2.7 on 2023-12-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0002_pokemoncard_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
